# Generated by Django 4.2.1 on 2023-05-20 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('sex', models.BooleanField()),
                ('music_network', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('last_join', models.DateField()),
                ('first_join', models.DateField()),
                ('is_superuser', models.BooleanField()),
                ('is_staff', models.BooleanField()),
                ('phone', models.CharField(max_length=20)),
                ('avatar', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialNetworkApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_text', models.CharField(max_length=255)),
                ('post_date', models.DateField()),
                ('published', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialNetworkApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text_comment', models.CharField(max_length=255)),
                ('comment_date', models.DateField()),
                ('self', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialNetworkApp.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialNetworkApp.user')),
            ],
        ),
    ]
